---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: hace
spec:
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: 10.100.100.1:5000/srigi/hace/webserver
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: hace
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webserver
  namespace: hace
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: www.hace.test
      http:
        paths:
          - path: /
            backend:
              serviceName: webserver
              servicePort: 8000
