---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: database-migrations.0
  namespace: hace
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: database-migration
          image: host.docker.internal:5000/srigi/hace/app
          imagePullPolicy: Always
          env:
            - name: APP_DEBUG
              value: '0'
          command: ['sh', '-c', 'wait-for-it database:5432 && bin/console migrations:continue --no-interaction']
      restartPolicy: Never
