---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: database-migration.0
  namespace: hace
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: database-migration
          image: 192.168.0.101:5000/srigi/hace
          env:
            - name: APP_DEBUG
              value: '0'
            - name: APP_HOST_PROTO
              value: http
            - name: APP_HOST_URI
              value: www.hace.test:30080
          command: ['sh', '-c', 'wait-for-it database:5432 && bin/console migrations:continue --no-interaction']
          imagePullPolicy: Always
      restartPolicy: Never
