---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa
  namespace: hace
spec:
  selector:
    matchLabels:
      app: spa
  template:
    metadata:
      labels:
        app: spa
    spec:
      containers:
        - name: spa
          image: 192.168.0.101:5000/srigi/hace/spa
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: spa
  namespace: hace
spec:
  selector:
    app: spa
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spa
  namespace: hace
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: spa.doveah.com
      http:
        paths:
          - path: /
            backend:
              serviceName: spa
              servicePort: 8000
